[build]
  base = "frontend"
  command = "npx pnpm install && npx pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-pnpm"

[build.environment]
  NODE_VERSION = "18"